---
targets:
  - name: "ヒロハタ"
    url: "http://hiro-hata.com/"
    sources:
    - type: rss
      url: "http://hiro-hata.com/rss"
    - type: facebook
      id: "619180321492100"
  - name: "MOVIN'ON"
    url: "http://coworking-hiroshima.com/"
    sources:
    - type: facebook
      id: "723399384347509"
  - name: "Shakehands"
    url: "http://www.shakehands.jp/"
    sources:
      - type: facebook
        id: "592127770838621"
  - name: "安芸津よし"
    url: "http://akitsu.co/"
    sources:
      - type: rss
        url: http://akitsu.co/feed
  - name: "tecre"
    url: "http://tecre.jp/"
    sources:
    - type: rss
      url: http://tecre.jp/feed/
  - name: "キマグレミーティング"
    url: "https://www.facebook.com/kimaguremeeting"
    sources:
    - type: facebook
      id: "501348703275034"
  - name: "PocketPlan"
    url: "http://pocketplan.wix.com/pocketplan"
    sources:
    - type: facebook
      id: "115520338533947"
  - name: "広島の楽しい100人"
    url: "http://hiroshima.100person.jp"
    sources:
    - type: facebook
      id: "1427131820895292"
  - name: "殿倶楽部"
    url: "https://www.facebook.com/tonoclub.info"
    sources:
    - type: facebook
      id: "121120534647214"
  - name: "子どもキャリア塾"
    url: "http://kodomo-career.com/"
    sources:
    - type: rss
      url: http://kodomo-career.com/feed
  - name: "メガフォン"
    url: "https://m-ph.org"
    sources:
    - type: rss
      url: "https://github.com/tsuchim/megaphone/commits/master.atom"
    - type: facebook
      id: "649742641811073"
  - name: "パークマップ広島"
    url: "http://parkmap.eiel.info"
    sources:
    - type: facebook
      id: "449921165167160"
  - name: "スマホで学習！＆ネットで工場見学！"
    url: "http://www.hyogo-intercampus.ne.jp/gallery/ictkyouzai/"
    sources:
    - type: facebook
      id: "312502515550676"
  - name: "すごい広島"
    url: "http://great-h.github.io/"
    sources:
    - type: facebook
      id: "393886870753964"
